version: '3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
    restart: on-failure
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    restart: on-failure
  gateway:
    build: ./nginx/
    ports:
      - ${PORT_DOCKER}
    volumes:
      - static:/staticfiles
      - media:/app/media/
    restart: on-failure
