version: '3'

volumes:
  pg_data_production:
  media:
  static_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    restart: on-failure
  backend:
    image: levtigrovich/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media/
    restart: on-failure
  frontend:
    image: levtigrovich/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    restart: on-failure
  gateway:
    image: levtigrovich/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/app/media/
    ports:
      - ${PORT_DOCKER}
    restart: on-failure
